### ISSUE TITLE
ng build success but throwing error on ng serve -- return new error

### ISSUE THREAD

**Issue by jagdishj** [webpack/webpack-sources#144]
I am getting the below issue in my angular project on ng serve but ng build is successful. 

I have done the below trials to resolve the error
trial 1: Removed the .angular folder and node modules folder and tried to install the modules again but no luck.
trial 2: removed the angular and node packages and tried to install again but got same error.

Error : 
node_modules\webpack-sources\lib\SizeOnlySource.js:16
                return new Error(
                       ^

Error: Content and Map of this Source is not available (only size() is supported)
    at SizeOnlySource._error (node_modules\webpack-sources\lib\SizeOnlySource.js:16:10)
    at SizeOnlySource.buffer (node_modules\webpack-sources\lib\SizeOnlySource.js:30:14)
    at _isSourceEqual (node_modules\webpack\lib\util\source.js:21:51)
    at isSourceEqual (node_modules\webpack\lib\util\source.js:43:17)
    at Compilation.emitAsset (node_modules\webpack\lib\Compilation.js:4215:9)
    at node_modules\webpack\lib\Compiler.js:553:28
    at node_modules\webpack\lib\Compiler.js:1183:17
    at eval (eval at create (node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:13:1)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by alexander-akait** [comment]
Please open an issue in `angular-cli`, I think it was fixed in the latest stable release

**Comment by jagdishj** [comment]
thank you for your quick response, I have updated my angular to the latest version and confirmed using ng update. but still issue persists.
i have opened the issue in angular cli - https://github.com/angular/angular/issues/44996

**Comment by jagdishj** [comment]
finally got the solution 
the issue is resolved by altering the app.module page to force angular to throw errors and then undo it and tried to run the code.

Note: in my trials, I have done cache clear many times but still it's not resolved at that time.

**Comment by jagdishj** [comment]
finally got the solution
the issue is resolved by altering the app.module page to force angular to throw errors and then undo it and tried to run the code.

Note: in my trials, I have done cache clear many times but still it's not resolved at that time.

**Comment by DiegoCoderpillar** [comment]
> finally got the solution the issue is resolved by altering the app.module page to force angular to throw errors and then undo it and tried to run the code.

@jagdishj 
Can you explain this better?

**Comment by jagdishj** [comment]
i was getting issue when i tried to run the existing code (which is downloaded from company account github).
the application throwing the error points to node modules file. as mentioned in above thread.

to resolve the issue i have deleted the node modules folder in angular project. and modified the ng module file to download the modules again.
